### ISSUE TITLE
Wrong url for daily Achievements.

### ISSUE THREAD

**Issue by Frigerius** [xhsun/gw2wrapper#17]
There is a wrong URL in ur getCurrentDailyAchievements(). It queries https://api.guildwars2.com/v2/achievement/daily instead of https://api.guildwars2.com/v2/achievements/daily (u missed a "s")

**Comment by Frigerius** [comment]
ah and errorResponse = new Gson().fromJson(error, ErrorResponse.class); for {"error":"not found"} produces a null String in ErrorResponse (ErrorCode line 33)

**Comment by xhsun** [comment]
I'm aware of the bug in checkErrorResponse() and it was fixed in v1.2.1
Thanks for pointing the wrong url for achievements, I have no idea how I missed that when I was testing

**Comment by Frigerius** [comment]
Great, thx for the fast fix.
