### ISSUE TITLE
Refactor Sync and Async Request Class

### ISSUE THREAD

**Issue by xhsun** [xhsun/gw2wrapper#43]
*This issue is related to #42.*

The `AsynchronousRequest` and `SynchronousRequest` classes are each around 3000 lines long, which means that they are a pain to work with and a pain to maintain. Thus I want to break them down to more manageable sizes.

Instead of split the requests by sync or async, I want to split them by the API endpoints. For example, all requests corresponds to `/v2/account/*` will be grouped together.

**Comment by MiniClem** [comment]
I'm on it, async requests maybe finished soon
